# Generated by Django 5.1.2 on 2024-10-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_drf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'USER'), ('admin', 'ADMIN')], default='user', max_length=20),
        ),
    ]
