# Generated by Django 5.1.2 on 2024-10-21 07:43
# '0002_user_role'

from django.db import migrations
from django.contrib.auth.hashers import make_password  # Importa el hash de contraseñas

def create_admin_user(apps, _):
    """ Obtains the User model and creates an admin user. """
    User = apps.get_model('blog_drf', 'User')
    
    # Create an admin user
    admin_user = User(
        username='admin',
        email='admin@example.com',
        is_staff=True,
        is_superuser=True,
        is_active=True,
        role='admin'  
    )
    # Generate the hashed password
    admin_user.password = make_password('admin123')
    # Save the user
    admin_user.save()

class Migration(migrations.Migration):
    """ Create migration to create an admin user. """

    dependencies = [
        ('blog_drf', '0002_user_role'),  # Replace with the correct previous migration
    ]

    operations = [
        migrations.RunPython(create_admin_user),
    ]


